import type { LucideIcon } from 'lucide-react';
import {
    Activity,
    AlertTriangle,
    ArrowUpDown,
    Award,
    BarChart3,
    BookOpen,
    Briefcase,
    Bus,
    Calculator,
    Calendar,
    CalendarCheck,
    CalendarDays,
    CalendarX,
    CheckCircle,
    CheckCircle2,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Columns3,
    Cpu,
    Database,
    DollarSign,
    Download,
    Eye,
    FileDown,
    FileSpreadsheet,
    FileText,
    Filter,
    GraduationCap,
    HardDrive,
    Layers,
    Library,
    Lightbulb,
    Mail,
    Megaphone,
    MessageSquare,
    MousePointerClick,
    Phone,
    PieChart,
    Pin,
    Printer,
    School,
    Server,
    Settings,
    Shield,
    ShieldCheck,
    Star,
    TrendingUp,
    UserCheck,
    UserCog,
    UserPlus,
    Users,
    UserX,
    Video,
    Wallet,
    Zap,
} from 'lucide-react';

/** Map of icon names to Lucide icon components used across the dashboard. */
export const iconMap: Record<string, LucideIcon> = {
    Activity,
    AlertTriangle,
    ArrowUpDown,
    Award,
    BarChart3,
    BookOpen,
    Briefcase,
    Bus,
    Calculator,
    Calendar,
    CalendarCheck,
    CalendarDays,
    CalendarX,
    CheckCircle,
    CheckCircle2,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Columns3,
    Cpu,
    Database,
    DollarSign,
    Download,
    Eye,
    FileDown,
    FileSpreadsheet,
    FileText,
    Filter,
    GraduationCap,
    HardDrive,
    Layers,
    Library,
    Lightbulb,
    Mail,
    Megaphone,
    MessageSquare,
    MousePointerClick,
    Phone,
    PieChart,
    Pin,
    Printer,
    School,
    Server,
    Settings,
    Shield,
    ShieldCheck,
    Star,
    TrendingUp,
    UserCheck,
    UserCog,
    UserPlus,
    Users,
    UserX,
    Video,
    Wallet,
    Zap,
};

/** Icon name type derived from the icon map keys. */
export type IconName = keyof typeof iconMap;

/** Resolves an icon name string to its Lucide icon component. */
export function getIcon(name: string): LucideIcon {
    return iconMap[name] ?? FileText;
}
