import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import LayoutClient from "./layout-client";
import { auth } from "@/lib/auth";


export default async function RootLayout({ children, auth: authModal }: Readonly<{ children: React.ReactNode; auth: React.ReactNode }>) {
    const session = await auth();

    const user = session?.user ? {
        name: session.user.name || 'User',
        email: session.user.email || '',
        role: session.user.role || 'user',
        avatar: session.user.image,
    } : undefined;

    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
                <Provider>
                    <LayoutClient user={user}>{children}</LayoutClient>
                    {authModal}
                </Provider>
            </body>
        </html>
    );
}

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
